name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          registry-url: https://registry.npmjs.org
          cache: npm
          node-version-file: package.json

      - name: Restore npm cache
        uses: actions/cache@v3
        id: restore-npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}

      - name: Install dependencies
        run: |
          if [ ${{ steps.restore-npm-cache.outputs.cache-hit }} = true ]
          then
            echo "Skipping npm ci."
          else
            npm ci
          fi

      - name: Cache npm dependencies
        uses: actions/cache@v3
        if: ${{ steps.restore-npm-cache.outputs.cache-hit }} != true
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json')}}

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      # TODO: Publish to npm registry